name: "Build Backend"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v29
    - run: nix flake check
    - run: nix build .#backend
