name: Create Release

# Tag a release (e.g. `v1.2.3`) to build a signed APK and attach it to a GitHub release.
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: SeineEloquenz/ci/.github/workflows/android-release.yml@main
    with:
      working-directory: ./app
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
